services:
  oteljob:
    profiles: ["standalone"]
    build:
      context: ./standalone
    stdin_open: true
    command:
      - -no-translation=${OTELJOB_NO_TRANSLATION:-false}
    networks:
      - otelnet

  observer:
    profiles: ["observer"]
    build:
      context: ./observer
    command:
      - -no-translation=${OBSERVER_NO_TRANSLATION:-false}
    networks:
      - otelnet

  otel-collector:
    profiles: ["standalone", "observer"]
    build:
      context: ./otelcollector
    depends_on:
      - prometheus
    volumes:
      - ./otelcol-config.compose.yaml:/etc/otelcol-contrib/config.yaml:ro
    environment:
      - OTELCOL_RW_TRANSLATION_STRATEGY=${OTELCOL_RW_TRANSLATION_STRATEGY:-UnderscoreEscapingWithSuffixes}
      - OTELCOL_RW_PROTOBUF_MESSAGE=${OTELCOL_RW_PROTOBUF_MESSAGE:-prometheus.WriteRequest}
    command:
      - --config=/etc/otelcol-contrib/config.yaml
      - --feature-gates=${OTELCOL_FEATURE_GATES:-}
    networks:
      - otelnet

  prometheus:
    profiles: ["standalone", "observer"]
    build:
      context: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --web.enable-otlp-receiver
      - --log.level=debug
    networks:
      - otelnet

networks:
  otelnet:
    driver: bridge
