receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'my_job'
          scrape_interval: 5s
          static_configs:
            - targets: ['oteljob:9464']

exporters:
  debug:
    verbosity: detailed
  otlp_http:
    metrics_endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
    tls:
      insecure: true
  prometheus_remote_write:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
    external_labels:
      path: remote_write

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [debug, otlp_http, prometheus_remote_write]
